- build.sbt
- project/build.sbt
Just an update of the libs dependencies for master branch.
> version bump

- scalarx/shared/src/main/scala/rx/Core.scala
- scalarx/shared/src/main/scala/rx/Macros.scala
- scalarx/shared/src/main/scala/rx/package.scala
- scalarx/shared/src/test/scala/rx/AdvancedTests.scala
- scalarx/shared/src/test/scala/rx/BasicTests.scala
- scalarx/shared/src/test/scala/rx/Util.scala
Squashed other PR
This is 0.3.0 with compile time checking dynamic RxCtx stuff.
> 0.3.0-SNAPSHOT

- readme.md
The old ones aren't resolvable
> Update maven coordinates

- build.sbt
- project/build.sbt
- readme.md
- scalarx/jvm/src/test/scala/rx/EventedTests.scala
- scalarx/shared/src/main/scala/rx/Core.scala
- scalarx/shared/src/main/scala/rx/async/package.scala
- scalarx/shared/src/main/scala/rx/opmacros/Operators.scala
- scalarx/shared/src/main/scala/rx/package.scala
- scalarx/shared/src/test/scala/rx/AdvancedTests.scala
- scalarx/shared/src/test/scala/rx/AsyncTests.scala
- scalarx/shared/src/test/scala/rx/CombinatorTests.scala
Doh! Obs leaked..
Also bumps scala.js version to 0.6.6 and version to 0.3.1.-SNAPSHOT.
> Fixed leaky obs problem

- readme.md
You can't have the first thing users try fail!
> Update first readme example to work with 0.3.1

- .travis.yml
- build.sbt
- project/build.properties
- project/build.sbt
- scalarx/shared/src/main/scala-2.12/rx/opmacros/Compat.scala
- scalarx/shared/src/test/scala-2.12/rx/CompileErrorTests.scala
- scalarx/shared/src/test/scala/rx/BasicTests.scala
> Bump to scala 2.12.0

- readme.md
The first example doesn't compile.
> Fixing the first example on the readme

- scalarx/shared/src/main/scala/rx/opmacros/Operators.scala
- scalarx/shared/src/test/scala/rx/BasicTests.scala
- scalarx/shared/src/test/scala/rx/CombinatorTests.scala
I'm not sure how to fix this yet. I thought about implementing `flatMap` with `Rx`, like written in the test, but I was not able to do that...
fixes #79
> Fix flatmap diamond leak

- build.sbt
- scalarx/shared/src/main/scala/rx/Rx.scala
- scalarx/shared/src/main/scala/rx/Var.scala
- scalarx/shared/src/main/scala/rx/async/package.scala
- scalarx/shared/src/main/scala/rx/opmacros/Factories.scala
- scalarx/shared/src/main/scala/rx/opmacros/Operators.scala
- scalarx/shared/src/test/scala/rx/AdvancedTests.scala
- scalarx/shared/src/test/scala/rx/BasicTests.scala
Port of #65 
Please review if I did everything correctly.
> Add sourcecode.Name to toString

- scalarx/shared/src/main/scala/rx/Var.scala
- scalarx/shared/src/test/scala/rx/BidirectionalVarOperators.scala
I don't understand why this test is failing... Any ideas?
> Activate multiset Zoomed Var test

- scalarx/shared/src/main/scala/rx/Rx.scala
- scalarx/shared/src/test/scala/rx/BasicTests.scala
@fdietze I *think* its ok to do this, in that it is morally equivalent to the private[this] accessor - but im not an expert on scala variance and when it can blow up.
> Unchecked Variance

- scalarx/shared/src/test/scala/rx/BidirectionalVarOperators.scala
While hunting for a bug, I was writing a test for mapRead to assure it triggers correctly. It passes, so I still need to find the problem in my application code :)
> add test for mapRead triggers

- .jitpack.yml
The workaround is not needed anymore. (https://github.com/jitpack/jitpack.io/issues/1887)
> Remove Jitpack workaround

- scalarx/shared/src/main/scala/rx/Rx.scala
- scalarx/shared/src/main/scala/rx/Var.scala
- scalarx/shared/src/test/scala/rx/BasicTests.scala
> kill observers when killing a variable

- bench/src/main/scala/Propagate.scala
- bench/src/main/scala/RxRecalc.scala
- bench/src/main/scala/Subscribe.scala
- build.sbt
This PR is on top of #129.
Here is the sbt command to run all benchmarks on JVM and JS:
```
> ; cd benchJVM ;set mainClass in Compile := Some("rx.bench.RxRecalc"); run ;set mainClass in Compile := Some("rx.bench.Subscribe"); run ;set mainClass in Compile := Some("rx.bench.Propagate"); run; cd benchJS ;set mainClass in Compile := Some("rx.bench.RxRecalc"); clean; run ;set mainClass in Compile := Some("rx.bench.Subscribe"); clean; run ;set mainClass in Compile := Some("rx.bench.Propagate"); clean; run
```
> Add some Benchmarks

- build.sbt
- scalarx/shared/src/main/scala/rx/Rx.scala
- scalarx/shared/src/main/scala/rx/Var.scala
- scalarx/shared/src/main/scala/rx/async/package.scala
- scalarx/shared/src/main/scala/rx/opmacros/Factories.scala
- scalarx/shared/src/main/scala/rx/opmacros/Operators.scala
- scalarx/shared/src/test/scala/rx/AdvancedTests.scala
- scalarx/shared/src/test/scala/rx/BasicTests.scala
* Save some intermediate allocations when building collections
* Inline some small functions
* Remove sourcecode dependency. This might be debatable, as it is nice for debugging, but I am not sure we should store the variable name in every rx.
> Performance improvements

- build.sbt
This adds extra checks to the resulting code
> Remove checkinit option

- readme.md
There are four options listed not two. I was a bit confused when read.
> Small error in readme file, update readme.md

- build.sbt
I think I resolved the jitpack build issues...
> Reactivate benchmarking

- readme.md
I think this library is not experimental anymore ;)
> Remove "experimental" from readme
